### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by rmorlok** [appleton/rspec_tap#5]
My company can't use the library unless we know the license for it. Could you please add a license?

**Comment by appleton** [comment]
All done, thanks for the reminder!

**Comment by rmorlok** [comment]
Thanks Andrew! Any chance you could bump the gem version with the license?

https://rubygems.org/gems/rspec_tap/

**Comment by appleton** [comment]
Bumped to 0.2.0 and published ✅

**Comment by rmorlok** [comment]
Awesome! Thank you!
